name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ocaml_env: ${{ steps.env.outputs.ocaml_env }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OCaml and opam
        run: |
          sudo apt update
          sudo apt install -y m4 curl unzip build-essential
          curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh | sh

      - name: Initialize opam
        id: env
        run: |
          eval $(opam init --disable-sandboxing --shell=sh --yes)
          opam switch create 5.1.0 --yes || true
          eval $(opam env)
          opam install dune --yes
          echo "::set-output name=ocaml_env::$(opam env)"
  
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup OCaml environment
        run: eval ${{ needs.setup.outputs.ocaml_env }}
      
      - name: Build project with dune
        run: dune build
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup OCaml environment
        run: eval ${{ needs.setup.outputs.ocaml_env }}
      
      - name: Run tests
        run: dune runtest
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup OCaml environment
        run: eval ${{ needs.setup.outputs.ocaml_env }}
      
      - name: Prepare and deploy static files
        run: |
          rm -rf _ghpages
          mkdir _ghpages
          cp -r src/static/* _ghpages/
          cd _ghpages
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/<your-username>/<your-repo>.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy static site $(date '+%Y-%m-%d %H:%M:%S')"
          git push --force origin gh-pages
