name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OPAM
        run: |
          sudo apt update
          sudo apt install -y m4 curl build-essential unzip
          export OPAMROOT=$HOME/.opam
          bash -c "sh <(curl -fsSL https://opam.ocaml.org/install.sh)" -- --prefix=$HOME/.local
          export PATH="$HOME/.local/bin:$PATH"
          opam init --disable-sandboxing --yes
          eval $(opam env)
          opam switch create 5.1.0 --yes || true
          eval $(opam env)
          opam install dune --yes
        shell: bash

      - name: Build
        run: |
          eval $(opam env)
          dune build
        shell: bash

      # - name: Test
      #   run: |
      #     eval $(opam env)
      #     dune runtest
      #   shell: bash

      - name: Deploy to gh-pages
        run: |
          rm -rf _ghpages
          mkdir _ghpages
          cp -r src/static/* _ghpages/
          cd _ghpages
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/<your-username>/<your-repo>.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy static site $(date '+%Y-%m-%d %H:%M:%S')"
          git push --force origin gh-pages
        shell: bash
